import type { INodeProperties } from 'n8n-workflow';

function show(resource: string, operations: string[]): INodeProperties['displayOptions'] {
  return { show: { resource: [resource], operation: operations } };
}

function mountField(resource: string, operations: string[], placeholder: string): INodeProperties {
  return {
    displayName: 'Mount Path',
    name: 'mount',
    type: 'string',
    default: '',
    placeholder,
    description: 'Override the mount from credentials. Leave empty to use the credential default',
    displayOptions: show(resource, operations),
  };
}

export const nodeProperties: INodeProperties[] = [
  {
    displayName: 'Resource',
    name: 'resource',
    type: 'options',
    noDataExpression: true,
    options: [
      { name: 'KV Secret', value: 'kv', description: 'Static infrastructure secrets (KV v1/v2)' },
      { name: 'Lease', value: 'lease', description: 'Look up, renew, or revoke dynamic credential leases' },
      { name: 'Database', value: 'database', description: 'Dynamic and static database credentials' },
      { name: 'SSH', value: 'ssh', description: 'OTP, signed certificates, and issued keys' },
      { name: 'AWS', value: 'aws', description: 'IAM users and STS credentials' },
      { name: 'Azure', value: 'azure', description: 'Azure service principals and static roles' },
      { name: 'GCP', value: 'gcp', description: 'GCP access tokens and service account keys' },
      { name: 'System', value: 'system', description: 'Health and token lookup' },
    ],
    default: 'kv',
  },
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: { show: { resource: ['kv'] } },
    options: [
      { name: 'Read', value: 'read', action: 'Read a KV secret', description: 'Read a static secret at a path' },
      { name: 'Write', value: 'write', action: 'Write a KV secret', description: 'Create or update a secret version' },
      { name: 'Rotate', value: 'rotate', action: 'Rotate a KV secret', description: 'Write a new KV version (KV has no native rotate)' },
      { name: 'Patch', value: 'patch', action: 'Patch a KV secret', description: 'Merge-patch fields on KV v2' },
      { name: 'List', value: 'list', action: 'List KV secrets', description: 'List keys under a path' },
      { name: 'Delete', value: 'delete', action: 'Delete a KV secret', description: 'Soft-delete latest or specific versions' },
      { name: 'Undelete', value: 'undelete', action: 'Undelete KV versions', description: 'Restore soft-deleted KV v2 versions' },
      { name: 'Destroy', value: 'destroy', action: 'Destroy KV versions', description: 'Permanently destroy KV v2 versions' },
      { name: 'Get Metadata', value: 'getMetadata', action: 'Get KV metadata', description: 'Read version-agnostic metadata' },
      { name: 'Update Metadata', value: 'updateMetadata', action: 'Update KV metadata', description: 'Set custom_metadata and version settings' },
      { name: 'Delete Metadata', value: 'deleteMetadata', action: 'Delete KV metadata', description: 'Delete a key and all versions' },
    ],
    default: 'read',
  },
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: { show: { resource: ['lease'] } },
    options: [
      { name: 'Lookup', value: 'lookup', action: 'Look up a lease', description: 'Inspect lease TTL and metadata' },
      { name: 'Renew', value: 'renew', action: 'Renew a lease', description: 'Extend a renewable lease' },
      { name: 'Revoke', value: 'revoke', action: 'Revoke a lease', description: 'Revoke immediately (sync). Does not expose revoke-force' },
    ],
    default: 'lookup',
  },
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: { show: { resource: ['database'] } },
    options: [
      { name: 'Generate Credentials', value: 'generateCredentials', action: 'Generate database credentials' },
      { name: 'Generate Static Credentials', value: 'generateStaticCredentials', action: 'Read static database credentials' },
      { name: 'Rotate Role', value: 'rotateRole', action: 'Rotate a static database role' },
      { name: 'Rotate Root', value: 'rotateRoot', action: 'Rotate database root credentials' },
    ],
    default: 'generateCredentials',
  },
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: { show: { resource: ['ssh'] } },
    options: [
      { name: 'Generate OTP', value: 'generateOtp', action: 'Generate an SSH OTP' },
      { name: 'Sign Certificate', value: 'sign', action: 'Sign an SSH public key' },
      { name: 'Issue Key', value: 'issue', action: 'Issue an SSH key and certificate' },
    ],
    default: 'sign',
  },
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: { show: { resource: ['aws'] } },
    options: [
      { name: 'Generate IAM Credentials', value: 'generateIam', action: 'Generate AWS IAM credentials' },
      { name: 'Generate STS Credentials', value: 'generateSts', action: 'Generate AWS STS credentials' },
      { name: 'Rotate Root', value: 'rotateRoot', action: 'Rotate AWS root credentials' },
    ],
    default: 'generateIam',
  },
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: { show: { resource: ['azure'] } },
    options: [
      { name: 'Generate Credentials', value: 'generateCredentials', action: 'Generate Azure credentials' },
      { name: 'Generate Static Credentials', value: 'generateStaticCredentials', action: 'Read Azure static credentials' },
      { name: 'Rotate Role', value: 'rotateRole', action: 'Rotate an Azure static role' },
      { name: 'Rotate Root', value: 'rotateRoot', action: 'Rotate Azure root credentials' },
    ],
    default: 'generateCredentials',
  },
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: { show: { resource: ['gcp'] } },
    options: [
      { name: 'Generate Access Token', value: 'generateAccessToken', action: 'Generate a GCP access token' },
      { name: 'Generate Service Account Key', value: 'generateServiceAccountKey', action: 'Generate a GCP service account key' },
      { name: 'Rotate Root', value: 'rotateRoot', action: 'Rotate GCP root credentials' },
      { name: 'Rotate Roleset', value: 'rotateRoleset', action: 'Rotate a GCP roleset account' },
      { name: 'Rotate Roleset Key', value: 'rotateRolesetKey', action: 'Rotate a GCP roleset key' },
    ],
    default: 'generateAccessToken',
  },
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: { show: { resource: ['system'] } },
    options: [
      { name: 'Health', value: 'health', action: 'Check Vault health' },
      { name: 'Lookup Self', value: 'lookupSelf', action: 'Look up the current token (token id redacted)' },
    ],
    default: 'health',
  },

  mountField('kv', ['read', 'write', 'rotate', 'patch', 'list', 'delete', 'undelete', 'destroy', 'getMetadata', 'updateMetadata', 'deleteMetadata'], 'secret'),
  {
    displayName: 'Secret Path',
    name: 'secretPath',
    type: 'string',
    default: '',
    required: true,
    placeholder: 'infra/ssh/bastion',
    displayOptions: show('kv', ['read', 'write', 'rotate', 'patch', 'delete', 'undelete', 'destroy', 'getMetadata', 'updateMetadata', 'deleteMetadata']),
  },
  {
    displayName: 'List Path',
    name: 'secretPath',
    type: 'string',
    default: '',
    placeholder: 'infra/',
    description: 'Path prefix to list. Empty lists the mount root',
    displayOptions: show('kv', ['list']),
  },
  {
    displayName: 'Version',
    name: 'secretVersion',
    type: 'number',
    default: 0,
    typeOptions: { minValue: 0 },
    description: 'KV v2 version to read. 0 means latest',
    displayOptions: show('kv', ['read']),
  },
  {
    displayName: 'Secret Data',
    name: 'secretData',
    type: 'json',
    default: '{}',
    required: true,
    displayOptions: show('kv', ['write', 'rotate', 'patch']),
  },
  {
    displayName: 'CAS Version',
    name: 'cas',
    type: 'number',
    default: -1,
    description: 'Check-and-set version for KV v2. -1 skips CAS. 0 allows write only if the key does not exist',
    displayOptions: show('kv', ['write', 'rotate', 'patch']),
  },
  {
    displayName: 'Versions',
    name: 'versions',
    type: 'string',
    default: '',
    placeholder: '1,2',
    description: 'Comma-separated version numbers. Empty delete removes the latest version',
    displayOptions: show('kv', ['delete', 'undelete', 'destroy']),
  },
  {
    displayName: 'Metadata',
    name: 'metadataBody',
    type: 'json',
    default: '{"max_versions": 10, "cas_required": false, "custom_metadata": {}}',
    displayOptions: show('kv', ['updateMetadata']),
  },

  {
    displayName: 'Lease ID',
    name: 'leaseId',
    type: 'string',
    default: '',
    required: true,
    placeholder: 'aws/creds/deploy/abcd',
    displayOptions: show('lease', ['lookup', 'renew', 'revoke']),
  },
  {
    displayName: 'Increment (seconds)',
    name: 'increment',
    type: 'number',
    default: 0,
    typeOptions: { minValue: 0 },
    description: 'Requested lease extension. 0 lets Vault use the role default',
    displayOptions: show('lease', ['renew']),
  },

  mountField('database', ['generateCredentials', 'generateStaticCredentials', 'rotateRole', 'rotateRoot'], 'database'),
  {
    displayName: 'Role Name',
    name: 'roleName',
    type: 'string',
    default: '',
    required: true,
    displayOptions: show('database', ['generateCredentials', 'generateStaticCredentials', 'rotateRole', 'rotateRoot']),
  },

  mountField('ssh', ['generateOtp', 'sign', 'issue'], 'ssh'),
  {
    displayName: 'Role Name',
    name: 'roleName',
    type: 'string',
    default: '',
    required: true,
    displayOptions: show('ssh', ['generateOtp', 'sign', 'issue']),
  },
  {
    displayName: 'IP Address',
    name: 'ipAddress',
    type: 'string',
    default: '',
    displayOptions: show('ssh', ['generateOtp']),
  },
  {
    displayName: 'Username',
    name: 'username',
    type: 'string',
    default: '',
    displayOptions: show('ssh', ['generateOtp', 'sign', 'issue']),
  },
  {
    displayName: 'Public Key',
    name: 'publicKey',
    type: 'string',
    typeOptions: { rows: 4 },
    default: '',
    required: true,
    displayOptions: show('ssh', ['sign']),
  },
  {
    displayName: 'Cert Type',
    name: 'certType',
    type: 'options',
    options: [
      { name: 'User', value: 'user' },
      { name: 'Host', value: 'host' },
    ],
    default: 'user',
    displayOptions: show('ssh', ['sign', 'issue']),
  },
  {
    displayName: 'Valid Principals',
    name: 'validPrincipals',
    type: 'string',
    default: '',
    displayOptions: show('ssh', ['sign', 'issue']),
  },
  {
    displayName: 'TTL',
    name: 'ttl',
    type: 'string',
    default: '',
    placeholder: '30m',
    displayOptions: show('ssh', ['sign', 'issue']),
  },
  {
    displayName: 'Key Type',
    name: 'keyType',
    type: 'options',
    options: [
      { name: 'rsa', value: 'rsa' },
      { name: 'ed25519', value: 'ed25519' },
      { name: 'ecdsa', value: 'ecdsa' },
    ],
    default: 'ed25519',
    displayOptions: show('ssh', ['issue']),
  },
  {
    displayName: 'Key Bits',
    name: 'keyBits',
    type: 'number',
    default: 0,
    displayOptions: show('ssh', ['issue']),
  },

  mountField('aws', ['generateIam', 'generateSts', 'rotateRoot'], 'aws'),
  {
    displayName: 'Role Name',
    name: 'roleName',
    type: 'string',
    default: '',
    required: true,
    displayOptions: show('aws', ['generateIam', 'generateSts']),
  },
  {
    displayName: 'TTL',
    name: 'ttl',
    type: 'string',
    default: '',
    placeholder: '1h',
    displayOptions: show('aws', ['generateIam', 'generateSts']),
  },
  {
    displayName: 'Role ARN',
    name: 'roleArn',
    type: 'string',
    default: '',
    displayOptions: show('aws', ['generateSts']),
  },
  {
    displayName: 'Role Session Name',
    name: 'roleSessionName',
    type: 'string',
    default: '',
    displayOptions: show('aws', ['generateSts']),
  },

  mountField('azure', ['generateCredentials', 'generateStaticCredentials', 'rotateRole', 'rotateRoot'], 'azure'),
  {
    displayName: 'Role Name',
    name: 'roleName',
    type: 'string',
    default: '',
    required: true,
    displayOptions: show('azure', ['generateCredentials', 'generateStaticCredentials', 'rotateRole']),
  },

  mountField('gcp', ['generateAccessToken', 'generateServiceAccountKey', 'rotateRoot', 'rotateRoleset', 'rotateRolesetKey'], 'gcp'),
  {
    displayName: 'Account Type',
    name: 'gcpAccountType',
    type: 'options',
    options: [
      { name: 'Roleset', value: 'roleset' },
      { name: 'Static Account', value: 'static-account' },
      { name: 'Impersonated Account', value: 'impersonated-account' },
    ],
    default: 'roleset',
    displayOptions: show('gcp', ['generateAccessToken', 'generateServiceAccountKey']),
  },
  {
    displayName: 'Account Name',
    name: 'roleName',
    type: 'string',
    default: '',
    required: true,
    displayOptions: show('gcp', ['generateAccessToken', 'generateServiceAccountKey', 'rotateRoleset', 'rotateRolesetKey']),
  },
  {
    displayName: 'Key Algorithm',
    name: 'keyAlgorithm',
    type: 'options',
    options: [
      { name: 'KEY_ALG_UNSPECIFIED', value: 'KEY_ALG_UNSPECIFIED' },
      { name: 'KEY_ALG_RSA_2048', value: 'KEY_ALG_RSA_2048' },
      { name: 'KEY_ALG_RSA_3072', value: 'KEY_ALG_RSA_3072' },
      { name: 'KEY_ALG_RSA_4096', value: 'KEY_ALG_RSA_4096' },
    ],
    default: 'KEY_ALG_RSA_2048',
    displayOptions: show('gcp', ['generateServiceAccountKey']),
  },
  {
    displayName: 'Key Type',
    name: 'gcpKeyType',
    type: 'options',
    options: [
      { name: 'TYPE_JSON', value: 'TYPE_JSON' },
      { name: 'TYPE_PKCS12_FILE', value: 'TYPE_PKCS12_FILE' },
    ],
    default: 'TYPE_JSON',
    displayOptions: show('gcp', ['generateServiceAccountKey']),
  },

  {
    displayName: 'Mask Secret Values',
    name: 'maskSecrets',
    type: 'boolean',
    default: true,
    description: 'Replace sensitive keys in the node output. Disable only when a downstream node must use the raw secret',
  },
  {
    displayName: 'Mask Keys (Regex)',
    name: 'maskRegex',
    type: 'string',
    default: '',
    placeholder: '(password|token|secret|key|credential|private)',
    displayOptions: { show: { maskSecrets: [true] } },
  },
];
